### ISSUE TITLE
kitchen-ec2 version 0.9.4 ssh transport is broken

### ISSUE THREAD

**Issue by scarolan** [test-kitchen/kitchen-ec2#154] opened 2015-06-08 04:01 UTC
It attempts to log onto the internal IP address instead of the external one now, rendering kitchen completely useless in EC2.  Please fix ASAP, we need this for customers!

       Waiting for SSH service on 172.31.3.87:22, retrying in 3 seconds
       Waiting for SSH service on 172.31.3.87:22, retrying in 3 seconds
       Waiting for SSH service on 172.31.3.87:22, retrying in 3 seconds

**Comment by tyler-ball** [comment] 2015-06-08 14:40
Closing as a duplicate of https://github.com/test-kitchen/kitchen-ec2/issues/148 which is fixed in version 0.9.5 (just released)

**Closed by tyler-ball** 2015-06-08 14:40 UTC
