### ISSUE TITLE
Kitchen attempts to log in before sshd is ready

### ISSUE THREAD

**Issue by scarolan** [test-kitchen/kitchen-ec2#85] opened 2014-12-27 14:31 UTC
This is on the plain vanilla CentOS 6.5 AMI from the marketplace.  Kitchen fails to log in the first time i run 'kitchen converge', then the second time I run it succeeds.  I think it should wait maybe 5-10 seconds after port 22 is open to allow the machine to become fully ready.

```
-----> Creating <frontend-2-centos-65>...
       Creating <>...
       If you are not using an account that qualifies under the AWS
       free-tier, you may be charged to run these suites. The charge
       should be minimal, but neither Test Kitchen nor its maintainers
       are responsible for your incurred costs.
       EC2 instance <i-99d44395> created.
.........       (server ready)
       Waiting for 54.149.191.16:22...
       Waiting for 54.149.191.16:22...
       (ssh ready)

       Finished creating <frontend-2-centos-65> (3m17.39s).
-----> Converging <frontend-2-centos-65>...
       Preparing files for transfer
       Resolving cookbook dependencies with Berkshelf 3.2.1...
       Removing non-cookbook files before transfer
>>>>>> Converge failed on instance <frontend-2-centos-65>.
>>>>>> Please see .kitchen/logs/frontend-2-centos-65.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Authentication failed for user root@54.149.191.16
>>>>>> ----------------------
```

**Comment by gmiranda23** [comment] 2015-01-08 07:25
Confirmed.  I got around this by setting
  ssh_timeout: 5
  ssh_retries: 5

Perhaps this should be a setting managed in amis.json?

**Comment by tyler-ball** [comment] 2015-02-10 00:22
I'm going to try and repro this so I can see where in the code it is failing - it may make sense to hardcode retry logic in there, or default the `ssh_timeout` and `ssh_restries` config to be greater for ec2 instances.

Do you know the AMI you used off the top of your head?  Or should I see this with any AMI?

**Comment by tyler-ball** [comment] 2015-05-19 17:41
Hey @scarolan - can you try this again with the latest version of kitchen-ec2 (0.9.0) and see if this is still an issue?  We updated to use the Test Kitchen 1.4 logic which greatly improved transport issues.

**Comment by tyler-ball** [comment] 2015-05-28 20:18
I'm going to go ahead and close this since I haven't gotten a response - please re-open if you're still having problems with the latest version of kitchen-ec2!

**Closed by tyler-ball** 2015-05-28 20:18 UTC
Labels: Feedback Requested, Triaged

**Comment by gmiranda23** [comment] 2015-05-28 21:38
I made a chance to try this out and I'm still having access issues for the initial ssh connection, though for slightly different reasons now.

$ kitchen setup
-----> Starting Kitchen (v1.4.0)
-----> Creating <default-centos-64>...
       Creating <>...
If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

       Instance <i-fb72eb0c> requested.
       EC2 instance <i-fb72eb0c> created.
       Waited 0/300s for instance <i-fb72eb0c> to become ready.
       Waited 5/300s for instance <i-fb72eb0c> to become ready.
       Waited 10/300s for instance <i-fb72eb0c> to become ready.
       Waited 15/300s for instance <i-fb72eb0c> to become ready.
       Waited 20/300s for instance <i-fb72eb0c> to become ready.
       EC2 instance <i-fb72eb0c> ready.
       Waiting for SSH service on ec2-52-25-141-157.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-52-25-141-157.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-52-25-141-157.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-52-25-141-157.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-52-25-141-157.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-52-25-141-157.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       Waiting for SSH service on ec2-52-25-141-157.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
root@ec2-52-25-141-157.us-west-2.compute.amazonaws.com's password:
root@ec2-52-25-141-157.us-west-2.compute.amazonaws.com's password:
root@ec2-52-25-141-157.us-west-2.compute.amazonaws.com's password:
       Waiting for SSH service on ec2-52-25-141-157.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       [SSH] Established
       Finished creating <default-centos-64> (2m20.17s).
[ ... ]

It's the correct SSH key.  I should note that during that time, in a separate session, I can login with the specified credentials.  The initial attempt bombs out (I simply enter nothing for password), SSH tries again and this time it works.  That is happening consistently.

$ chef -v
Chef Development Kit Version: 0.6.0
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

$ chef gem list kitchen-ec2
*** LOCAL GEMS ***
kitchen-ec2 (0.9.2)

Relevant bits of .kitchen.yml
driver:
  name: ec2
  aws_ssh_key_id: my-ssh-key
  region: us-west-2
  require_chef_omnibus: true
  instance_type: m3.medium
  security_group_ids: [ "default" ]

transport:
  ssh_key: /Users/gmiranda/.ssh/my-ssh-key
  username: root
