### ISSUE TITLE
destroying non-existence instance and marking passing test as failed

### ISSUE THREAD

**Issue by kzw** [test-kitchen/kitchen-ec2#247] opened 2016-04-28 19:43 UTC
I frequently get the following error message

```
       Finished in 0.07649 seconds (files took 0.27544 seconds to load)
       [32m1 example, 0 failures[0m

       Finished verifying <syslog-filter-ubuntu-1204> (0m12.55s).
       Finished testing <syslog-filter-ubuntu-1204> (6m16.34s).
-----> Destroying <syslog-filter-ubuntu-1204>...
       EC2 instance <i-fe980263> destroyed.
       Finished destroying <syslog-filter-ubuntu-1204> (0m0.41s).
-----> Cleaning up any prior instances of <sentry7-nginx-ubuntu-1204>
-----> Destroying <sentry7-nginx-ubuntu-1204>...
-----> Destroying <sentry7-nginx-ubuntu-1204>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #destroy action: [The instance ID 'i-d4a2b54e' does not exist]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
```

I could not find this instance ID it is trying to destroy in the full log.  I also attach the output from `kitchen diagnose --all`

[k.txt](https://github.com/test-kitchen/kitchen-ec2/files/241320/k.txt)

**Comment by KrestenKjaer** [comment] 2016-06-10 07:18
I have the same problem.

**Comment by darwin67** [comment] 2017-03-06 23:54
i'm seeing the same problem and this seem to be related to `kitchen-ec2` failing to create an instance in the previous settings and proceeds with the latter without recording the new instance's id when you run `kitchen test`.

![error](https://cloud.githubusercontent.com/assets/5746693/23635521/329aa3a6-0285-11e7-9794-0d1792881169.png)

**Comment by mattray** [comment] 2017-07-13 04:04
I get this issue if the instance has been deleted and no longer exists. No way to ```kitchen destroy --force``` either

```
C:\Users\chef\cookbooks\bjc-ecommerce [master]> kitchen destroy
-----> Starting Kitchen (v1.16.0)
-----> Destroying <default-ubuntu-1404>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [The instance ID 'i-05e00373048a1c8c9' does not exist] on default-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by cheeseplus** [comment] 2017-11-20 23:19
Closing this one as a dupe of #191

**Closed by cheeseplus** 2017-11-20 23:19 UTC
