### ISSUE TITLE
Missing AMI generates Nil::NilClass error

### ISSUE THREAD

**Issue by scarolan** [test-kitchen/kitchen-ec2#284] opened 2016-10-19 15:27 UTC
If your AMI is not valid (for example, Amazon deprecated the AMI and replaced it with an updated one), Test Kitchen fails with a very unhelpful "Nil::Nilclass" nomethod type error.  It should instead check to see if the AMI actually exists, and return a better error message if it doesn't.

**Comment by cheeseplus** [comment] 2017-02-13 17:49
Closing as dupe of #230

**Closed by cheeseplus** 2017-02-13 17:49 UTC
Labels: Documentation
