### ISSUE TITLE
`kitchen destroy` should not fail when EC2 instance doesn't exist

### ISSUE THREAD

**Issue by haidangwa** [test-kitchen/kitchen-ec2#356] opened 2017-11-29 18:46 UTC
kitchen-ec2 version: 1.3.2
Test Kitchen 1.16.0
ChefDK 1.5.0 (Mac)

In my use case, the EC2 instance that Test Kitchen spun up was still running for quite some time. In our organization, we monitor and terminate these instances if they are inadvertently left running for more than a few days. When `kitchen destroy` is run after the EC2 instances are long gone, Test Kitchen throws an error and fails. I think it should handle this gracefully and not fail.

```
kitchen destroy
-----> Starting Kitchen (v1.16.0)
-----> Destroying <default-chef12-rhel6>...
-----> Destroying <default-chef12-rhel7>...
       Finished destroying <default-chef12-rhel7> (0m0.00s).
-----> Destroying <default-chef13-rhel6>...
       Finished destroying <default-chef13-rhel6> (0m0.00s).
-----> Destroying <default-chef13-rhel7>...
       Finished destroying <default-chef13-rhel7> (0m0.00s).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [The instance ID 'i-09e1922a9a71c1c32' does not exist] on default-chef12-rhel6
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

In my case, the instance was already terminated, so the `kitchen destroy` should just update its metadata and not throw this failure.

Subsequent `kitchen list` shows this error:
```
kitchen list
Instance              Driver  Provisioner  Verifier  Transport  Last Action    Last Error
default-chef12-rhel6  Ec2     ChefZero     Busser    Rsync      Created        Aws::EC2::Errors::InvalidInstanceIDNotFound
default-chef12-rhel7  Ec2     ChefZero     Busser    Rsync      <Not Created>  <None>
default-chef13-rhel6  Ec2     ChefZero     Busser    Rsync      <Not Created>  <None>
default-chef13-rhel7  Ec2     ChefZero     Busser    Rsync      <Not Created>  <None>
```

It seems that I'm now blocked from testing the suite now that Test Kitchen can't _destroy_ the instance, see below:
```
kitchen test default-chef12-rhel6
-----> Starting Kitchen (v1.16.0)
-----> Cleaning up any prior instances of <default-chef12-rhel6>
-----> Destroying <default-chef12-rhel6>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [The instance ID 'i-09e1922a9a71c1c32' does not exist] on default-chef12-rhel6
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
Now, I have to manually delete the state file for that test suite: `rm .kitchen/default-chef12-rhel6.yml`

**Comment by cheeseplus** [comment] 2017-12-01 12:46
Dupe of #191 - kitchen expects to holistically manage any instances it is responsible for, if they get destroyed out of band it's somewhat expected to error in the general case. Clearly folks in cloud environments are yolo destroying things so we can make this less grating of halt but this is functionally correct behavior at this time, not a bug.

**Closed by cheeseplus** 2017-12-01 12:46 UTC
