### ISSUE TITLE
kitchen test is failed when ec2 intances were deleted automatically

### ISSUE THREAD

**Issue by SydOps** [test-kitchen/kitchen-ec2#278] opened 2016-09-13 01:33 UTC
We have an auto-run cronjob to clean any kitchen test ec2 instances if created more than 2 days. So when run the test on same role after several days, kitchen test will report the ec2 instance is not exist, and failed. 

In this case, I have to manually remove `.kitchen` folder, and re-run `kitchen test`

I'd like to continuously run the test, when `kitchen test` found the exist instance is gone, create a new one. 

What can I do?

**Comment by cheeseplus** [comment] 2017-02-17 00:36
This is effectively a dupe of - https://github.com/test-kitchen/kitchen-ec2/issues/275

**Closed by cheeseplus** 2017-02-17 00:36 UTC
