### ISSUE TITLE
AMI search provides wrong AMI for amazon linux

### ISSUE THREAD

**Issue by voroniys** [test-kitchen/kitchen-ec2#445] opened 2019-02-20 13:18 UTC
In my .kitchen.yml I have the following:
```
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-*
```
and I expect it will provide me the latest AMI for amazonlinux 2, which is at the moment of writting  `amzn2-ami-hvm-2.0.20190115-x86_64-gp2`
Nevertheless I constantly getting very outdated image `amzn2-ami-hvm-2017.12.0.20180509-x86_64-gp2`
Accordingly to the README file I have to have the most recent one. Something wrong with sorting?

**Comment by cheeseplus** [comment] 2019-02-20 21:59
Could you provide the kitchen-ec2 version details? Typically you can just name the platform `amazon-2` and it will execute this search which is a bit different from yours https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/aws/standard_platform/amazon2.rb#L30 the actual sorting hasn't much changed and you can see the decisions it's filtering on fairly easily in https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/aws/standard_platform.rb

**Comment by voroniys** [comment] 2019-02-22 07:24
My version is
kitchen-ec2 (2.4.0)
And I fully disagree with you that my query is not specific enough. You set the criteria:
- HVM images over paravirtual
- SSD support over magnetic drives
- 64-bit over 32-bit
- The most recently created image (to pick up patch releases)
Accordingly to this criteria I should never get `amzn2-ami-hvm-2017.12.0.20180509-x86_64-gp2`, just because `ami-hvm-2.0.20190115-x86_64-gp2` is much more recent while 3 first conditions are the same.
Just from experiment I conclude that the 4th criteria implemented based on image name, and not on creation date.
I took this conclusion based on the fact that with search criteria 
name: amzn2-ami-hvm-*-x86_64-gp2
I'm getting outdated AMI, while with
name: amzn2-ami-hvm-2.0.*-x86_64-gp2
I'm getting the right one.

**Comment by cheeseplus** [comment] 2019-02-22 20:27
I'm unable to reproduce this with either configuration in the `us-east-1` region:

```
platforms:
  - name: amazon2
  - name: search_1
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-*
  - name: search_2
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-hvm-*-x86_64-gp2
```
All of the above iterations I get `amzn2-ami-hvm-2.0.20190115-x86_64-gp2 (ami-035be7bafff33b6b6)`

If you are able to reproduce this reliably then I suspect it might be region specific or there are other mitigating configuration factors. We would need a full `kitchen.yml`, the logs from the run, the region being used, and ideally output from `kitchen diagnose`. Provide those and we can investigate further. I'd also double check the version of `kitchen-ec2` as there were fixes for Amazon 2 that shipped in 2.4.0 which is what the above configuration was run against.

**Comment by voroniys** [comment] 2019-02-25 14:08
I'm using eu-west-1 (Ireland) region.

**Comment by cheeseplus** [comment] 2019-02-25 19:29
I'll try to replicate there, what I suspect is that how Amazon loaded/tagged/dated the images there is inherently bad and we're just passing along said "bad data". If that's the case then it's more an AWS problem than our sorting but I'll see if I can figure out why and if there is any mitigation w/o accounting for each region specifically (which would be a nightmare).

**Comment by cheeseplus** [comment] 2019-02-26 01:27
Still unable to replicate with the following condfiguration

```
driver:
  name: ec2
  region: "eu-west-1"

provisioner:
  name: chef_zero

platforms:
  - name: amazon2
    # - name: amazon2-2019
  - name: search-1
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-*
  - name: search-2
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-hvm-*-x86_64-gp2
```
Test-kitchen gets the expected `amzn2-ami-hvm-2.0.20190218-x86_64-gp2 (ami-0838da7c1467f590c)` for all three permutations. At this point I feel like we should verify that you're actually using the version of kitchen-ec2 expected and also get the output of `kitchen diagnose`.

If using ChefDK:
`chef -v`
`chef gem list kitchen-ec2`

If using your own Ruby/Bundler:
`which kitchen`
`kitchen --version`
`gem list kitchen-ec2`

**Comment by voroniys** [comment] 2019-02-26 05:55
Hi,
thanks for the effort, I hope we can figure this out together. In my system 100% replicable.
``
$ chef -v
Chef Development Kit Version: 3.6.57
chef-client version: 14.8.12
delivery version: master (5fb4908da53579c9dcf4894d4acf94d2d9ee6475)
berks version: 7.0.7
kitchen version: 1.24.0
inspec version: 3.2.6

$ chef gem list kitchen-ec2

*** LOCAL GEMS ***

kitchen-ec2 (2.4.0)
````

Here is my .kitchen.yml:
```
driver:
  name: ec2
  aws_ssh_key_id: Kitchen-key
  security_group_filter:
    tag:   'Name'
    value: 'shared-kitchen'
  region: eu-west-1
  availability_zone: b
  require_chef_omnibus: true
  subnet_filter:
    tag:   'Name'
    value: 'app-eu-west-1b'
  instance_type: t3.micro
  tags:
    Name: 'test-kitchen'
  associate_public_ip: false
  interface: private_dns

transport:
  ssh_key: ~/.chef/kitchen-rsa
  connection_timeout: 10
  connection_retries: 5


provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: amazon2
    driver:
      image_search:
        owner-id: "137112412989"
        name: amzn2-ami-*
    attributes:
suites:
  - name: default
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```
And finaly the result:
```
$ kitchen create default-amazon2
-----> Starting Kitchen (v1.24.0)
-----> Creating <default-amazon2>...
       Detected platform: amazon2 version 2017.12. on x86_64. Instance Type: t3.micro. Default username: ec2-user (default).
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

       Instance <i-0bfe3386d9e9aa254> requested.
       Polling AWS for existence, attempt 0...
       Attempting to tag the instance, 0 retries
       EC2 instance <i-0bfe3386d9e9aa254> created.
       Waited 0/300s for instance <i-0bfe3386d9e9aa254> volumes to be ready.
       Waited 0/300s for instance <i-0bfe3386d9e9aa254> to become ready.
       Waited 5/300s for instance <i-0bfe3386d9e9aa254> to become ready.
       Waited 10/300s for instance <i-0bfe3386d9e9aa254> to become ready.
       Waited 15/300s for instance <i-0bfe3386d9e9aa254> to become ready.
       Waited 20/300s for instance <i-0bfe3386d9e9aa254> to become ready.
       EC2 instance <i-0bfe3386d9e9aa254> ready (hostname: ip-172-17-5-139.eu-west-1.compute.internal).
       Waiting for SSH service on ip-172-17-5-139.eu-west-1.compute.internal:22, retrying in 3 seconds
       [SSH] Established
       Finished creating <default-amazon2> (0m28.96s).
-----> Kitchen is finished. (0m33.63s)
svoroniy@bastion:~/chef-repo/cookbooks/ul_common$ kitchen login default-amazon2
Last login: Tue Feb 26 05:27:28 2019 from ip-172-17-1-88.eu-west-1.compute.internal

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
51 package(s) needed for security, out of 369 available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-172-17-5-139 ~]$ curl http://169.254.169.254/latest/meta-data/ami-id
ami-921423eb
```


And finaly part of diagnose output:
```
---
timestamp: 2019-02-26 05:53:02 UTC
kitchen_version: 1.24.0
instances:
  default-amazon2:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: ip-172-17-5-198.eu-west-1.compute.internal
      last_action: create
      last_error:
      server_id: i-0a0b83b906168afd6
      username: ec2-user
    driver:
      associate_public_ip: false
      availability_zone: b
      aws_access_key_id:
      aws_secret_access_key:
      aws_session_token:
      aws_ssh_key_id: Kitchen-key
      block_duration_minutes:
      ebs_optimized: false
      http_proxy:
      iam_profile_name:
      image_id: ami-921423eb
      image_search:
        owner-id: '137112412989'
        name: amzn2-ami-*
      instance_initiated_shutdown_behavior:
      instance_type: t3.micro
      interface: private_dns
      kitchen_root: "/home/svoroniy/chef-repo/cookbooks/test"
      log_level: :info
      name: ec2
      pre_create_command:
      private_ip_address:
      region: eu-west-1
      retry_limit: 3
      retryable_sleep: 5
      retryable_tries: 60
      security_group_filter:
        tag: Name
        value: shared-kitchen
      security_group_ids:
      shared_credentials_profile:
      skip_cost_warning: false
      spot_price:
      ssl_verify_peer: true
      subnet_filter:
        tag: Name
        value: app-eu-west-1b
      tags:
        Name: test-kitchen
      tenancy: default
      test_base_path: "/home/svoroniy/chef-repo/cookbooks/test/test/integration"
      user_data:
      username:
```

**Comment by cheeseplus** [comment] 2019-02-26 16:43
Curious what happens if you change to:

```
platforms:
  - name: amazon2
```

And let the built-in handling/search work. I recognize it doesn't explain the behaviour you are seeing but there appear to be at least two workarounds: 1) letting the built-in search work 2) providing a longer, more specific search term

I'll try adding in the values you've provided above one by one to see if that changes the results I'm seeing but also wanted to note the workarounds so that you're not blocked.

**Comment by voroniys** [comment] 2019-02-26 19:20
For the searches:
 `name: amzn2-ami-hvm-*-x86_64-gp2`
  giving me outdated AMI, while with
  `name: amzn2-ami-hvm-2.0.*-x86_64-gp2`
  I'm getting the right one.

If I remove search and leave only amazon2 it is giving me a right one and this is as expected, since by default search conditions is:
` "name" => version ? "amzn2-ami-hvm-2.0.#{version}*" : "amzn2-ami-hvm-2.0.*",`
and the key to get the right value is to provide `-2.0.*` in the search. With 2.0 it is working, without - not.

I'm not blocked, since I've found already, that adding 2.0 solving the issue.

**Comment by marcparadise** [comment] 2021-04-07 17:56
Given the workaround and research already done, it does look like this is more related to the data amazon is retaining/providing in search results; kitchen ec2 is reporting back what it's given.  Closing this out, since a workaround has been found.

**Closed by marcparadise** 2021-04-07 17:56 UTC
